SOURCE_VOCAB_SIZE = 5980
TARGET_VOCAB_SIZE = 4830
RULE_NUM = 228

EMBED_DIM = 300
RULE_EMBED_DIM = 300
QUERY_DIM = 200
LSTM_STATE_DIM = 300
DECODER_ATT_HIDDEN_DIM = 100
POINTER_NET_HIDDEN_DIM = 100

MAX_QUERY_LENGTH = 70
MAX_EXAMPLE_ACTION_NUM = 100

EPOCH_NUM = 100
BATCH_SIZE = 10

# define actions
APPLY_RULE = 0
GEN_TOKEN = 1
COPY_TOKEN = 2
GEN_COPY_TOKEN = 3

config_info = dict([(v, globals()[v]) for v in dir() if not v.startswith('__')])

ACTION_NAMES = {APPLY_RULE: 'APPLY_RULE',
                GEN_TOKEN: 'GEN_TOKEN',
                COPY_TOKEN: 'COPY_TOKEN',
                GEN_COPY_TOKEN: 'GEN_COPY_TOKEN'}